name: edusync_hub
description: "Context-Aware Learning Platform."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1

  # Routing
  go_router: ^12.1.3

  # DI & Serialization
  get_it: ^7.6.4
  injectable: ^2.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Network Requests
  dio: ^5.2.1
  connectivity_plus: ^5.0.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^1.4.0
  uuid: ^4.2.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9

  # UI
  flutter_screenutil: ^5.9.0
  gap: ^2.0.0
  flutter_hooks: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

  # Build Runner & Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.0
  injectable_generator: ^2.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.2

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

# To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#     - family: familjenGroteskTextTheme()
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
